# coding: utf-8

"""
    math.js web service

    [math.js](math.js) is available as a RESTful API. Evaluations can be done via [GET](https://api.mathjs.org/#get) or [POST](https://api.mathjs.org/#post) requests. The duration per evaluation of this free service is limited to 10 seconds.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import re  # noqa: F401

# python 2 and python 3 compatibility library
import six

from swagger_client.api_client import ApiClient


class DefaultApi(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    Ref: https://github.com/swagger-api/swagger-codegen
    """

    def __init__(self, api_client=None):
        if api_client is None:
            api_client = ApiClient()
        self.api_client = api_client

    def root_get(self, expr, **kwargs):  # noqa: E501
        """Calculate given expression with GET  # noqa: E501

        Calculate expression given in a query parameter  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.root_get(expr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str expr: The expression to be evaluated. The expression must be [url encoded](http://www.w3schools.com/tags/ref_urlencode.asp). (required)
        :param float precision: Number of significant digits in formatted output. Undefined by default.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.root_get_with_http_info(expr, **kwargs)  # noqa: E501
        else:
            (data) = self.root_get_with_http_info(expr, **kwargs)  # noqa: E501
            return data

    def root_get_with_http_info(self, expr, **kwargs):  # noqa: E501
        """Calculate given expression with GET  # noqa: E501

        Calculate expression given in a query parameter  # noqa: E501
        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.root_get_with_http_info(expr, async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param str expr: The expression to be evaluated. The expression must be [url encoded](http://www.w3schools.com/tags/ref_urlencode.asp). (required)
        :param float precision: Number of significant digits in formatted output. Undefined by default.
        :return: None
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['expr', 'precision']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method root_get" % key
                )
            params[key] = val
        del params['kwargs']
        # verify the required parameter 'expr' is set
        if ('expr' not in params or
                params['expr'] is None):
            raise ValueError("Missing the required parameter `expr` when calling `root_get`")  # noqa: E501

        collection_formats = {}

        path_params = {}

        query_params = []
        if 'expr' in params:
            query_params.append(('expr', params['expr']))  # noqa: E501
        if 'precision' in params:
            query_params.append(('precision', params['precision']))  # noqa: E501

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/', 'GET',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type=None,  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)

    def root_post(self, **kwargs):  # noqa: E501
        """Calculate given expression with POST  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.root_post(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Request body:
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """
        kwargs['_return_http_data_only'] = True
        if kwargs.get('async_req'):
            return self.root_post_with_http_info(**kwargs)  # noqa: E501
        else:
            (data) = self.root_post_with_http_info(**kwargs)  # noqa: E501
            return data

    def root_post_with_http_info(self, **kwargs):  # noqa: E501
        """Calculate given expression with POST  # noqa: E501

        This method makes a synchronous HTTP request by default. To make an
        asynchronous HTTP request, please pass async_req=True
        >>> thread = api.root_post_with_http_info(async_req=True)
        >>> result = thread.get()

        :param async_req bool
        :param Request body:
        :return: Response
                 If the method is called asynchronously,
                 returns the request thread.
        """

        all_params = ['body']  # noqa: E501
        all_params.append('async_req')
        all_params.append('_return_http_data_only')
        all_params.append('_preload_content')
        all_params.append('_request_timeout')

        params = locals()
        for key, val in six.iteritems(params['kwargs']):
            if key not in all_params:
                raise TypeError(
                    "Got an unexpected keyword argument '%s'"
                    " to method root_post" % key
                )
            params[key] = val
        del params['kwargs']

        collection_formats = {}

        path_params = {}

        query_params = []

        header_params = {}

        form_params = []
        local_var_files = {}

        body_params = None
        if 'body' in params:
            body_params = params['body']
        # HTTP header `Accept`
        header_params['Accept'] = self.api_client.select_header_accept(
            ['application/json'])  # noqa: E501

        # HTTP header `Content-Type`
        header_params['Content-Type'] = self.api_client.select_header_content_type(  # noqa: E501
            ['application/json'])  # noqa: E501

        # Authentication setting
        auth_settings = []  # noqa: E501

        return self.api_client.call_api(
            '/', 'POST',
            path_params,
            query_params,
            header_params,
            body=body_params,
            post_params=form_params,
            files=local_var_files,
            response_type='Response',  # noqa: E501
            auth_settings=auth_settings,
            async_req=params.get('async_req'),
            _return_http_data_only=params.get('_return_http_data_only'),
            _preload_content=params.get('_preload_content', True),
            _request_timeout=params.get('_request_timeout'),
            collection_formats=collection_formats)
