# coding: utf-8

# flake8: noqa
"""
    math.js web service

    [math.js](math.js) is available as a RESTful API. Evaluations can be done via [GET](https://api.mathjs.org/#get) or [POST](https://api.mathjs.org/#post) requests. The duration per evaluation of this free service is limited to 10 seconds.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

# import models into model package
from swagger_client.models.request import Request
from swagger_client.models.response import Response
