# coding: utf-8

"""
    math.js web service

    [math.js](math.js) is available as a RESTful API. Evaluations can be done via [GET](https://api.mathjs.org/#get) or [POST](https://api.mathjs.org/#post) requests. The duration per evaluation of this free service is limited to 10 seconds.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six


class Request(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'expr': 'Object',
        'precision': 'int'
    }

    attribute_map = {
        'expr': 'expr',
        'precision': 'precision'
    }

    def __init__(self, expr=None, precision=None):  # noqa: E501
        """Request - a model defined in Swagger"""  # noqa: E501
        self._expr = None
        self._precision = None
        self.discriminator = None
        self.expr = expr
        if precision is not None:
            self.precision = precision

    @property
    def expr(self):
        """Gets the expr of this Request.  # noqa: E501

        A string containing the expression to be evaluated, or an array with strings to be evaluated  # noqa: E501

        :return: The expr of this Request.  # noqa: E501
        :rtype: Object
        """
        return self._expr

    @expr.setter
    def expr(self, expr):
        """Sets the expr of this Request.

        A string containing the expression to be evaluated, or an array with strings to be evaluated  # noqa: E501

        :param expr: The expr of this Request.  # noqa: E501
        :type: Object
        """
        if expr is None:
            raise ValueError("Invalid value for `expr`, must not be `None`")  # noqa: E501

        self._expr = expr

    @property
    def precision(self):
        """Gets the precision of this Request.  # noqa: E501

        Number of significant digits in formatted output. Undefined by default.  # noqa: E501

        :return: The precision of this Request.  # noqa: E501
        :rtype: int
        """
        return self._precision

    @precision.setter
    def precision(self, precision):
        """Sets the precision of this Request.

        Number of significant digits in formatted output. Undefined by default.  # noqa: E501

        :param precision: The precision of this Request.  # noqa: E501
        :type: int
        """

        self._precision = precision

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(Request, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, Request):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
