# coding: utf-8

"""
    math.js web service

    [math.js](math.js) is available as a RESTful API. Evaluations can be done via [GET](https://api.mathjs.org/#get) or [POST](https://api.mathjs.org/#post) requests. The duration per evaluation of this free service is limited to 10 seconds.   # noqa: E501

    OpenAPI spec version: 1.0.0
    
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from models.response import Response  # noqa: E501
from swagger_client.rest import ApiException


class TestResponse(unittest.TestCase):
    """Response unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testResponse(self):
        """Test Response"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.response.Response()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
